import { writeFileSync } from 'fs'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import sharp from 'sharp'
import { createCanvas } from 'canvas'
import { synthesizeImage } from '../src/index'
