allowBuilds:
  canvas: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - canvas
  - esbuild
  - sharp

overrides:
  compare-func: "^2.0.0"
  flatted: "^3.4.2"
  form-data: "^4.0.4"
  handlebars: "^4.7.9"
  katex: "^0.16.21"
  lodash: "^4.17.24"
  lodash-es: "^4.17.24"
  rollup: "^4.59.0"
